image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1566.41141,    0.     ,  617.14046,
            0.     , 1566.72373,  532.83378,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.070705, 0.152044, -0.000230, 0.000285, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1553.73926,    0.     ,  616.90091,    0.     ,
            0.     , 1556.03003,  532.3679 ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]